.gitignore, Makefile, README.md, src/pinyin.cc, src/pinyin.h, test.sql
=> Fix build error in macOS

.gitignore, build-and-run, example.sql, src/entry.cc, src/pinyin.cc, src/simple_highlight.cc, src/simple_highlight.h, test/main.cpp, test/tokenizer_test.cc
=> impl simple_highlight_pos and simple_snippet

example.sql, src/entry.cc, src/pinyin.cc, src/simple_tokenizer.cc, src/simple_tokenizer.h
=> add flag to disable pinyin

test/CMakeLists.txt, test/CMakeLists.txt.in
=> fix gtest build issue

example.sql, src/pinyin.cc, src/simple_highlight.cc, src/simple_tokenizer.cc, src/simple_tokenizer.h, test/pinyin_test.cc, test/tokenizer_test.cc
Can't match single quote '
address #19
=> support match special chars

CMakeLists.txt, build-and-run, examples/cpp/CMakeLists.txt, examples/cpp/main.cc
=> add cpp examples

examples/cpp/main.cc
=> show how to use simple_query

example.sql, examples/cpp/main.cc, src/simple_tokenizer.cc, test/tokenizer_test.cc
The reason is explained in https://sqlite.org/forum/forumpost/6d161a2caa
Fix #19
=> fix match single quotes

.github/codecov.yml, .github/workflows/main.yml, CMakeLists.txt, build-and-run, src/CMakeLists.txt, test/CMakeLists.txt
Change-Id: Ic52cf4d2a15ab0b46652a9270bee1f752df923dc
=> add code coverage

src/simple_tokenizer.cc, test/pinyin_test.cc, test/tokenizer_test.cc
Change-Id: Ia763c19d9b240bfd770c15d914be9b73ea217ba1
=> add more tests

README.md, example-jieba.sql, examples/cpp/main.cc, src/entry.cc, src/simple_tokenizer.cc, src/simple_tokenizer.h
With this change, user can `select jieba_dict('/path/to/dict/')` to set the dict path before using jieba_query
Fix #37
=> add jieba_dict to set dict path

example-jieba.sql, example.sql, src/pinyin.cc, test/tokenizer_test.cc
=> match pinyin continusly

examples/cpp/main.cc, src/simple_tokenizer.cc, src/simple_tokenizer.h
Make load_extenstion fast
Related to #44
=> lazy init pinyin data

build-and-run, build-and-run-no-jieba
=> skip install bashmatic

examples/cpp/main.cc, src/pinyin.cc, src/pinyin.h
Improve startup time to 500ms
#44
=> remove regex dependency

.github/workflows/main.yml, src/CMakeLists.txt
=> fix build win32

.gitignore, README.md, examples/go/go.mod, examples/go/go.sum, examples/go/main.go, examples/go/run.sh
=> Add Go example

.github/workflows/main.yml, examples/node/better-sqlite3.js, examples/node/just-task.js, examples/node/package-lock.json, examples/node/package.json
=> add better-sqlite3 example

.github/workflows/main.yml
=> Bypass macOS security issue

README.md
=> Add C# example

src/simple_tokenizer.cc
Reverts wangfenjin/simple#159
根据 #158 这里的讨论，先 revert 这个 PR
debug 模式下 crash 短期影响不大，主要是提示可能的隐患，但是在我们这个场景中是安全的
=> Revert "修复 #158，Windows 下 Debug 版本 dll 崩溃问题"

.github/workflows/main.yml
=> support win-arm64
